import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import CartSidebarProvider from "@/context/CartSidebarContext";
import CartSidebar from "@/components/CartSidebar";
import WishlistSidebarProvider from "@/context/WishlistSidebarContext";
import WishlistSidebar from "@/components/WishlistSidebar";
import { store } from "./store";
import ReduxProvider from "@/components/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "todo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <ReduxProvider>
    <CartSidebarProvider>
      <WishlistSidebarProvider>
        <html lang="en">
          <body className={inter.className}>
            <Header />
            <CartSidebar />
            <WishlistSidebar/>
            {children}
            <Footer />
          </body>
        </html>
      </WishlistSidebarProvider>
    </CartSidebarProvider>
    </ReduxProvider>
  );
}
